---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: planktron-manager
  namespace: kube-system
secrets:
- name: planktron-manager-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: planktron-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: planktron-manager-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: planktron-manager-role
subjects:
- kind: ServiceAccount
  name: planktron-manager
  namespace: kube-system
